# Generated by Django 5.0.1 on 2026-05-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_producer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['producer', 'category', 'name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
