# Generated by Django 5.0.1 on 2026-04-18 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_initial'),
        ('producers', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Total de Visualizações')),
                ('total_favorites', models.PositiveIntegerField(default=0, verbose_name='Total de Favoritos')),
                ('total_phone_clicks', models.PositiveIntegerField(default=0, verbose_name='Cliques no Telefone')),
                ('total_whatsapp_clicks', models.PositiveIntegerField(default=0, verbose_name='Cliques no WhatsApp')),
                ('total_directions_clicks', models.PositiveIntegerField(default=0, verbose_name='Cliques em Rotas')),
                ('monthly_views', models.PositiveIntegerField(default=0, verbose_name='Visualizações do Mês')),
                ('monthly_favorites', models.PositiveIntegerField(default=0, verbose_name='Favoritos do Mês')),
                ('previous_month_views', models.PositiveIntegerField(default=0, verbose_name='Visualizações do Mês Anterior')),
                ('previous_month_favorites', models.PositiveIntegerField(default=0, verbose_name='Favoritos do Mês Anterior')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='producers.producerprofile', verbose_name='Produtor')),
            ],
            options={
                'verbose_name': 'Estatística do Produtor',
                'verbose_name_plural': 'Estatísticas dos Produtores',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('LOCATION_VIEW', 'Visualização de Localização'), ('LOCATION_CLICK', 'Clique em Localização'), ('PRODUCT_VIEW', 'Visualização de Produto'), ('PRODUCER_VIEW', 'Visualização de Produtor'), ('FAVORITE_ADD', 'Adicionou aos Favoritos'), ('FAVORITE_REMOVE', 'Removeu dos Favoritos'), ('PHONE_CLICK', 'Clique no Telefone'), ('WHATSAPP_CLICK', 'Clique no WhatsApp'), ('DIRECTIONS_CLICK', 'Clique em Rotas'), ('SEARCH', 'Busca')], max_length=20, verbose_name='Tipo de Atividade')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='locations.location', verbose_name='Localização')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='producers.producerprofile', verbose_name='Produtor')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='products.product', verbose_name='Produto')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que realizou a ação (pode ser null para usuários anônimos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analytics_a_created_b5efc6_idx'), models.Index(fields=['activity_type', '-created_at'], name='analytics_a_activit_c99d4e_idx'), models.Index(fields=['location', '-created_at'], name='analytics_a_locatio_deb450_idx'), models.Index(fields=['producer', '-created_at'], name='analytics_a_produce_719e6f_idx')],
            },
        ),
    ]
