# Generated by Django 5.0.1 on 2026-01-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=200, verbose_name='Nome da propriedade/negócio')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='producers/covers/', verbose_name='Imagem de capa')),
                ('has_organic_certification', models.BooleanField(default=False, verbose_name='Possui certificação orgânica')),
                ('certification_details', models.TextField(blank=True, verbose_name='Detalhes da certificação')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Perfil de Produtor',
                'verbose_name_plural': 'Perfis de Produtores',
            },
        ),
    ]
