# Generated by Django 5.0.1 on 2026-05-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Razão social'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=30, verbose_name='Inscrição municipal'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='state_registration',
            field=models.CharField(blank=True, max_length=30, verbose_name='Inscrição estadual'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Notas da verificação'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Analisado em'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='verification_status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING', 'Em análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='DRAFT', max_length=20, verbose_name='Status da verificação'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado para verificação em'),
        ),
    ]
