# Generated by Django 5.0.1 on 2026-01-19 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='locations/gallery/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Imagem de Localização',
                'verbose_name_plural': 'Imagens de Localizações',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do local')),
                ('location_type', models.CharField(choices=[('FAIR', 'Feira'), ('STORE', 'Loja'), ('FARM', 'Propriedade Rural'), ('DELIVERY', 'Entrega/Delivery'), ('OTHER', 'Outro')], default='FAIR', max_length=10, verbose_name='Tipo de local')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Imagem principal')),
                ('operation_days', models.CharField(blank=True, help_text='Ex: Segunda a Sábado', max_length=200, verbose_name='Dias de funcionamento')),
                ('operation_hours', models.CharField(blank=True, help_text='Ex: 7h às 12h', max_length=100, verbose_name='Horário de funcionamento')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='common.address', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'ordering': ['-created_at'],
            },
        ),
    ]
