# Generated by Django 5.0.1 on 2026-01-19 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('producers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='producers.producerprofile', verbose_name='Produtor'),
        ),
        migrations.AddField(
            model_name='location',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='locations', to='products.product', verbose_name='Produtos disponíveis'),
        ),
        migrations.AddField(
            model_name='locationimage',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='locations.location', verbose_name='Localização'),
        ),
    ]
