# Generated by Django 5.0.1 on 2026-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='suspended_by_billing',
            field=models.BooleanField(default=False, help_text='Definido automaticamente quando o plano expira e o limite de locais é excedido.', verbose_name='Suspenso por faturamento'),
        ),
    ]
