# Generated by Django 5.0.1 on 2026-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_subscriptionplan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('FREE', 'Gratuito'), ('BASIC', 'Básico'), ('PREMIUM', 'Premium')], max_length=20, unique=True),
        ),
    ]
