# Generated by Django 5.0.1 on 2026-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_subscriptionplan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle_months',
            field=models.PositiveSmallIntegerField(default=1, help_text='Meses cobertos por um único pagamento (1=mensal, 12=anual)'),
        ),
    ]
